# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 079879f
_src_path: git@github.com:vivienm/copier-copier.git
author_fullname: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_license: MIT
copyright_year: 2023
project_description: A Copier template for Copier templates!
project_name: Copier project template
repository_hosted: true
repository_name: copier-copier
repository_namespace: vivienm
repository_provider: github.com
repository_url: https://github.com/vivienm/copier-copier
