# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 8e9fcaa
_src_path: git@github.com:vivienm/copier-copier.git
copyright_holder: Vivien Maisonneuve
copyright_year: 2023
forge: github
github_repo: copier-copier
github_user: vivienm
license: MIT
project_description: A Copier template for Copier templates!
project_name: Copier project template
user_name: Vivien Maisonneuve
